import streamlit as st
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
import warnings
import os

warnings.filterwarnings('ignore')

# ==========================================
# 1. PAGE SETUP & ML INITIALIZATION
# ==========================================
st.set_page_config(page_title="Actuarial Risk & Reserving", layout="wide", page_icon="📊")
st.title("📊 Enterprise Risk & Capital Dashboard")
st.markdown("Multi-Tenant Workstation: Stochastic Pricing, Reserving, & Reinsurance Structuring")

@st.cache_resource
def train_reinsurance_tree():
    """Trains the ML model to recommend Reinsurance treaties based on risk/capital ratios."""
    X = np.array([
        [0.05, 0.1], [0.08, 0.2],  # Low loss ratio, low severity -> Retain (0)
        [0.15, 0.8], [0.20, 0.9],  # Medium loss ratio, high frequency -> Quota Share (1)
        [0.40, 0.3], [0.60, 0.2],  # High loss ratio, massive single severity -> Excess of Loss (2)
        [0.85, 0.9], [0.95, 0.8]   # Company killer (High ratio, high severity) -> Facultative (3)
    ])
    y = np.array([0, 0, 1, 1, 2, 2, 3, 3])
    tree = DecisionTreeClassifier(max_depth=3, random_state=42)
    tree.fit(X, y)
    return tree

decision_tree = train_reinsurance_tree()

# ==========================================
# 2. DATA LOADING & CLEANING
# ==========================================
@st.cache_data
def load_master_data():
    import os
    
    # 1. Dynamically find where dashboard.py lives (the 'scr' folder)
    current_dir = os.path.dirname(os.path.abspath(__file__))
    
    # 2. Step UP one level to the main 'ACTUARIAL DASHBOARD' folder
    parent_dir = os.path.dirname(current_dir)
    
    # 3. Build the two possible relative paths based on your setup
    path_in_root = os.path.join(parent_dir, 'prodliab_pos_98-07.csv')
    path_in_data = os.path.join(parent_dir, 'data', 'prodliab_pos_98-07.csv')
    
    # 4. Have Python automatically select the right one
    if os.path.exists(path_in_data):
        file_path = path_in_data
    elif os.path.exists(path_in_root):
        file_path = path_in_root
    else:
        raise FileNotFoundError("Could not find the CSV in the main folder or the data folder.")

    # Load and clean the data
    raw_data = pd.read_csv(file_path) 
    
    raw_data = raw_data.sort_values(['GRNAME', 'AccidentYear', 'DevelopmentLag'])
    raw_data['IncrementalPaid'] = raw_data.groupby(['GRNAME', 'AccidentYear'])['CumPaidLoss'].diff()
    raw_data['IncrementalPaid'] = raw_data['IncrementalPaid'].fillna(raw_data['CumPaidLoss'])
    
    clean_data = raw_data[raw_data['IncrementalPaid'] > 0]
    return clean_data

@st.cache_data
def load_capital_data():
    # Looks for the capital CSV generated by your capital_engine.py script
    capital_path = os.path.join('data', 'carrier_capital.csv')
    if os.path.exists(capital_path):
        return pd.read_csv(capital_path)
    return pd.DataFrame()

try:
    df = load_master_data()
except FileNotFoundError:
    st.error("Could not find the historical claims CSV. Please check the file path in Section 2.")
    st.stop()

# Load the capital data globally so Tab 4 can use it
df_capital = load_capital_data()

# ==========================================
# 3. SIDEBAR CONTROLS
# ==========================================
st.sidebar.header("🏢 Portfolio Selection")
company_list = sorted(df['GRNAME'].unique())
selected_company = st.sidebar.selectbox("Select Historical Portfolio:", company_list)

st.sidebar.markdown("---")
st.sidebar.header("🎲 Simulation Parameters")
iterations = st.sidebar.number_input("Monte Carlo Iterations:", min_value=1000, max_value=50000, value=10000, step=1000)
expected_claims = st.sidebar.slider("Expected Claims/Year (Frequency):", min_value=1, max_value=100, value=15)

company_data = df[df['GRNAME'] == selected_company].sort_values(['AccidentYear', 'DevelopmentLag'])
historical_losses = company_data['IncrementalPaid'].dropna().values

if len(historical_losses) == 0:
    st.warning("No historical loss data available for this company.")
    st.stop()

# ==========================================
# 4. CORE ENGINE (Runs before UI renders)
# ==========================================
@st.cache_data(show_spinner=False)
def fit_distributions(data_array):
    dist_names = ['lognorm', 'gamma', 'weibull_min', 'expon', 'pearson3']
    results = []
    for name in dist_names:
        try:
            dist = getattr(stats, name)
            params = dist.fit(data_array, floc=0) if name != 'pearson3' else dist.fit(data_array)
            log_likelihood = np.sum(dist.logpdf(data_array, *params))
            k = len(params)
            aic = 2 * k - 2 * log_likelihood
            if not np.isnan(aic) and not np.isinf(aic):
                results.append({'Distribution': name, 'AIC': aic, 'Params': params, 'Dist_Object': dist})
        except Exception:
            pass
    return pd.DataFrame(results).sort_values(by='AIC').reset_index(drop=True)

with st.spinner("Calculating stochastic models..."):
    leaderboard = fit_distributions(historical_losses)
    best_dist_row = leaderboard.iloc[0]
    active_dist = best_dist_row['Dist_Object']
    active_params = best_dist_row['Params']

@st.cache_data(show_spinner=False)
def run_simulation(_dist, params, expected_freq, iters):
    freqs = np.random.poisson(lam=expected_freq, size=iters)
    sims = np.array([np.sum(np.maximum(_dist.rvs(*params, size=f), 0)) if f > 0 else 0 for f in freqs])
    return sims

sim_results = run_simulation(active_dist, active_params, expected_claims, iterations)
var_99 = float(np.percentile(sim_results, 99))
expected_loss = float(np.mean(sim_results))

# ==========================================
# 5. UI TABS
# ==========================================
tab_home, tab_sim, tab_tri, tab_rein = st.tabs([
    "🏠 Executive Home", 
    "🎲 Stochastic Simulation", 
    "🔺 Loss Triangles", 
    "🛡️ Capital & Reinsurance"
])

# --- TAB 1: EXECUTIVE HOME (SUMMARY STATS) ---
with tab_home:
    st.header(f"Executive Summary: {selected_company}")
    st.markdown("High-level historical statistics and simulated future exposure.")
    
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Historical Claims Count", f"{len(historical_losses)}")
    col2.metric("Mean Historical Severity", f"${np.mean(historical_losses):,.0f}")
    col3.metric("Max Historical Single Loss", f"${np.max(historical_losses):,.0f}")
    col4.metric("Total Paid to Date", f"${np.sum(historical_losses):,.0f}")
    
    st.divider()
    st.subheader("Forward-Looking Risk Profile")
    st.info(f"Based on **{iterations:,}** Monte Carlo iterations using a **{best_dist_row['Distribution'].upper()}** distribution.")
    
    r1, r2 = st.columns(2)
    r1.metric("Expected Annual Loss (Mean)", f"${expected_loss:,.0f}")
    r2.metric("1-in-100 Year Shock Loss (99% VaR)", f"${var_99:,.0f}", delta="Tail Risk", delta_color="inverse")

# --- TAB 2: STOCHASTIC SIMULATION ---
with tab_sim:
    st.header("Monte Carlo Severity & Frequency Engine")
    
    col_ctrl, col_lead = st.columns([1, 2])
    with col_ctrl:
        st.subheader("Distribution Selection")
        selected_dist_name = st.selectbox("Active Distribution:", leaderboard['Distribution'].tolist(), index=0)
        
    with col_lead:
        st.subheader("🏆 Goodness-of-Fit Leaderboard")
        st.dataframe(leaderboard[['Distribution', 'AIC']].head(5), use_container_width=True)

    st.markdown("---")
    st.subheader("🎯 Value at Risk (VaR) & Range Analysis")
    
    max_sim = float(np.max(sim_results))
    val_95 = float(np.percentile(sim_results, 95))
    range_vals = st.slider("Select Loss Threshold Range:", 0.0, max_sim, (0.0, val_95), step=100.0, format="$%f")
    
    prob_in = np.mean((sim_results >= range_vals[0]) & (sim_results <= range_vals[1])) * 100
    prob_above = np.mean(sim_results > range_vals[1]) * 100

    m1, m2 = st.columns(2)
    m1.success(f"**Prob in Range:** {prob_in:.2f}%")
    m2.error(f"**Prob > ${range_vals[1]:,.0f} (Tail Risk):** {prob_above:.2f}%")

    fig, ax = plt.subplots(figsize=(10, 4))
    n, bins, patches = ax.hist(sim_results, bins=100, color='lightgray', edgecolor='black', alpha=0.7)
    for i in range(len(bins)-1):
        if range_vals[0] <= bins[i] <= range_vals[1]:
            patches[i].set_facecolor('royalblue')
    
    ax.axvline(var_99, color='red', linestyle='dashed', lw=2, label='99% VaR')
    ax.set_title(f"Simulated Annual Losses ({selected_dist_name.upper()})")
    ax.legend()
    st.pyplot(fig)

# --- TAB 3: LOSS DEVELOPMENT TRIANGLES ---
with tab_tri:
    st.header("Actuarial Loss Development Triangles")
    triangle = company_data.pivot_table(index='AccidentYear', columns='DevelopmentLag', values='CumPaidLoss', aggfunc='sum')
    
    st.subheader("Cumulative Paid Loss Triangle ($)")
    st.dataframe(triangle.style.background_gradient(cmap='Blues', axis=None).format("{:,.0f}", na_rep="-"), use_container_width=True)

    fig2, ax2 = plt.subplots(figsize=(10, 4))
    for acc_year in triangle.index:
        ax2.plot(triangle.columns, triangle.loc[acc_year], marker='o', label=f'AY {acc_year}')
    
    ax2.set_xlabel("Development Lag (Years)")
    ax2.set_ylabel("Cumulative Paid Loss ($)")
    ax2.set_title("Loss Development Trajectories")
    if len(triangle.index) <= 15:
        ax2.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    st.pyplot(fig2)

# --- TAB 4: CAPITAL & REINSURANCE ENGINE ---
with tab_rein:
    st.header("🛡️ Capital Adequacy & Reinsurance Strategy")
    st.markdown("Uses a Machine Learning Decision Tree to recommend reinsurance treaties based on the portfolio's simulated VaR vs. the Carrier's live surplus.")
    
    if df_capital.empty:
        st.warning("⚠️ Live capital data not found. Run `capital_engine.py` to populate carrier financials.")
    else:
        st.subheader("Target Carrier Financials")
        target_ticker = st.selectbox("Select Target Carrier for Solvency Test:", df_capital['Ticker'].tolist())
        
        carrier_info = df_capital[df_capital['Ticker'] == target_ticker].iloc[0]
        surplus_actual = carrier_info['Surplus_Billions'] * 1_000_000_000
        
        loss_ratio = var_99 / surplus_actual
        severity_ratio = 0.5 
        
        prediction = decision_tree.predict([[loss_ratio, severity_ratio]])[0]
        treaty_types = {
            0: "Net Retention (No Reinsurance Needed)",
            1: "Quota Share Treaty",
            2: "Excess of Loss (XoL) Treaty",
            3: "Facultative Placement (Extreme Risk)"
        }
        
        recommended_premium = var_99 * 0.01 * 1.15 if prediction > 0 else 0
        
        c1, c2 = st.columns(2)
        with c1:
            st.metric("Carrier Name", carrier_info['Company'])
            st.metric("Live Policyholder Surplus", f"${surplus_actual:,.0f}")
            st.metric("Portfolio Shock Loss (VaR)", f"${var_99:,.0f}")
            
        with c2:
            st.info(f"**Loss-to-Surplus Ratio:** {loss_ratio * 100:.4f}%")
            if prediction == 0:
                st.success(f"**Recommended Action:** {treaty_types[prediction]}")
            elif prediction == 3:
                st.error(f"**Recommended Action:** {treaty_types[prediction]}")
            else:
                st.warning(f"**Recommended Action:** {treaty_types[prediction]}")
            
            st.metric("Est. Reinsurance Premium (Burning Cost)", f"${recommended_premium:,.0f}")